version: 1
disable_existing_loggers: false

formatters:
  default: # For console - simpler output
    format: "%(levelname)s - %(message)s"

  detail: # For files - more context
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  # --- Console Handler ---
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
    level: INFO

  # --- File Handlers ---
  # These handlers filter messages based on their own level
  debug_file:
    class: logging.FileHandler
    formatter: detail
    filename: debug.log
    mode: a
    level: DEBUG

root:
  level: DEBUG # Set root level low to catch all desired messages for files
  handlers: [console, debug_file]
